### ISSUE TITLE
GeoJSON export produces JSON syntax errors

### ISSUE THREAD

**Issue by tuukka** [ad-freiburg/qlever-petrimaps#11]
I ran my query in QLever, opened the map view, and clicked "Export as GeoJSON". It worked otherwise, but the exported file was missing commas between some of the features as required to be valid JSON syntax.

In the FeatureCollection, some features are separated correctly by `}\n,{` but some are separated incorrectly by `}{` (no comma as required, and no new line either).

I had to run this shell command to add the commas and get rid of the syntax error:

```shell
sed -e 's/}{/},{/g' <export.json >fixed.json
```

That is, there were commas missing between the end of one feature and the beginning of the next one, and at least syntactically, there were no other errors.

I wasn't able to reproduce the problem with queries where the results are all points.

# Test case

For example, here's a query that produces 4 multipolygon results:
```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osm: <https://www.openstreetmap.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX osm2rdfkey: <https://osm2rdf.cs.uni-freiburg.de/rdf/key#>
SELECT DISTINCT ?item ?osm_id ?osmName ?image ?geometry WHERE {
  SERVICE <https://qlever.cs.uni-freiburg.de/api/wikidata> {
    SELECT ?item {
      ?item wdt:P31/wdt:P279* wd:Q473972 .
    }
  }
  ?osm_id osm2rdfkey:wikidata ?item .
  ?osm_id osmkey:boundary "protected_area" .
#  { ?osm_id rdf:type osm:way . } UNION { ?osm_id rdf:type osm:relation . }

  ?osm_id geo:hasGeometry/geo:asWKT ?geometry .
  ?osm_id osmkey:name ?osmName
}
ORDER BY ?item
LIMIT 4
```

Map view: [link](https://qlever.cs.uni-freiburg.de/mapui-petri/?query=PREFIX+geo%3A+%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E+PREFIX+osm%3A+%3Chttps%3A%2F%2Fwww.openstreetmap.org%2F%3E+PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+PREFIX+osmkey%3A+%3Chttps%3A%2F%2Fwww.openstreetmap.org%2Fwiki%2FKey%3A%3E+PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E+PREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E+PREFIX+osm2rdfkey%3A+%3Chttps%3A%2F%2Fosm2rdf.cs.uni-freiburg.de%2Frdf%2Fkey%23%3E+SELECT+DISTINCT+%3Fitem+%3Fosm_id+%3FosmName+%3Fimage+%3Fgeometry+WHERE+%7B+SERVICE+%3Chttps%3A%2F%2Fqlever.cs.uni-freiburg.de%2Fapi%2Fwikidata%3E+%7B+SELECT+%3Fitem+%7B+%3Fitem+wdt%3AP31%2Fwdt%3AP279*+wd%3AQ473972+%7D+%7D+%3Fosm_id+osm2rdfkey%3Awikidata+%3Fitem+.+%3Fosm_id+osmkey%3Aboundary+%22protected_area%22+.+%3Fosm_id+geo%3AhasGeometry%2Fgeo%3AasWKT+%3Fgeometry+.+%3Fosm_id+osmkey%3Aname+%3FosmName+%7D+ORDER+BY+%3Fitem+LIMIT+4&backend=https%3A%2F%2Fqlever.cs.uni-freiburg.de%2Fapi%2Fosm-planet)

The exported GeoJSON contains 12 features (a discrepancy?), between which there are 3 commas and 8 commas missing (for the extra features?).

Is it intentional that while MultiPoint collects the coordinates into one feature, MultiPolygon (and MultiLine) instead has `print` implementations that call `print` multiple times, e.g.:
```cpp
template <typename T>
void GeoJsonOutput::print(const MultiPolygon<T>& mpoly, json::Val attrs) {
  for (const auto& p : mpoly) print(p, attrs);
}

**Comment by patrickbr** [comment]
Thanks for reporting this! The GeoJSON export given under the link you provided is indeed syntactically incorrect. I will look into it!

**Comment by patrickbr** [comment]
This is now fixed in the latest master, @hannahbast can you update our official petrimaps instance?

**Comment by hannahbast** [comment]
@patrickbr I tried (I had to merge with uncommited changes of mine, my bad). Can you check whether the official version now does what it should regarding this issue?

**Comment by patrickbr** [comment]
@hannahbast, yes, everything is working now. In particular, the [example from above](https://qlever.cs.uni-freiburg.de/mapui-petri/?query=PREFIX+geo%3A+%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E+PREFIX+osm%3A+%3Chttps%3A%2F%2Fwww.openstreetmap.org%2F%3E+PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+PREFIX+osmkey%3A+%3Chttps%3A%2F%2Fwww.openstreetmap.org%2Fwiki%2FKey%3A%3E+PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E+PREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E+PREFIX+osm2rdfkey%3A+%3Chttps%3A%2F%2Fosm2rdf.cs.uni-freiburg.de%2Frdf%2Fkey%23%3E+SELECT+DISTINCT+%3Fitem+%3Fosm_id+%3FosmName+%3Fimage+%3Fgeometry+WHERE+%7B+SERVICE+%3Chttps%3A%2F%2Fqlever.cs.uni-freiburg.de%2Fapi%2Fwikidata%3E+%7B+SELECT+%3Fitem+%7B+%3Fitem+wdt%3AP31%2Fwdt%3AP279*+wd%3AQ473972+%7D+%7D+%3Fosm_id+osm2rdfkey%3Awikidata+%3Fitem+.+%3Fosm_id+osmkey%3Aboundary+%22protected_area%22+.+%3Fosm_id+geo%3AhasGeometry%2Fgeo%3AasWKT+%3Fgeometry+.+%3Fosm_id+osmkey%3Aname+%3FosmName+%7D+ORDER+BY+%3Fitem+LIMIT+4&backend=https%3A%2F%2Fqlever.cs.uni-freiburg.de%2Fapi%2Fosm-planet) can now be exported to GeoJSON. Thanks!
