### ISSUE TITLE
Broken pipe exception on high and rapid map zoom

### ISSUE THREAD

**Issue by Grandro** [ad-freiburg/qlever-petrimaps#9]
https://github.com/ad-freiburg/qlever-petrimaps/blob/338df822f68de3abaeed6f9241ad1ce7aeea36cd/src/qlever-petrimaps/server/Server.cpp#L869-L882

In line 875 I sometimes get a Broken pipe exception when zooming on high zoom (where object dots/heatmap are bigger). This can also happen when zooming out from high zoom again. I think it only happens when zooming rapidly.

**Comment by patrickbr** [comment]
I suspect this isn't a broken pipe *exception* (`write()` is a C function and therefore doesn't throw any exceptions), but a SIGPIPE signal.

Will try to replicate this and handle SIGPIPEs correctly here.

**Comment by patrickbr** [comment]
Can you try again using the latest master? SIGPIPE is now set to SIG_IGN explicitly in Server.cpp (it is already set so in `util::Server`, so I don't quite understand why you still received them). Additionally, all `write()` calls to the socket have been replaced by `send()` (`write()` with additional flags), and the `MSG_NOSIGNAL` flag is not always set).

Just out of curiosity: which OS are you using? I was unable to replicate this on an Ubuntu and a Debian system, even when adding a `sleep(10)`  before line 874 and closing the socket immediately after the request. I had to explicitly set the default signal handler for `SIGPIPE` get the behavior your described, so my guess is that some defaults differ between your system and our testing systems.

**Comment by Grandro** [comment]
Excuse my late reply. I am using Windows 11 + WSL but I was also not able to replicate the problem on Windows 10 + WSL back then. I just spent a few minutes rapidly zooming in and out, and the issue seems to be resolved. Thank you.
